name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Copiar código para o runner
      uses: actions/checkout@v4

    - name: Configurar ambiente Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependências
      run: npm install

    - name: Executar testes automatizados
      run: npm test

    - name: Simular Build do Docker
      run: |
        echo "Simulando a criação da imagem Docker..."
        docker build -t minha-api:latest .
